# Import Libraries

In [1]:
import datetime
import json

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import requests
from suds.client import Client
from Add_In_Queries import *

In [2]:
ptf = get_positions("PF72354", "01/01/2025")

/home/jovyan/notebooks/alto_studio/Risk/Analysis/Portfolio Review/Equity/Add_In_Queries.py:239: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  return pd.DataFrame(data,columns=columns).replace('soapenc:string',0)

In [4]:
ptf["positionWeight"] = ptf["positionWeight"].astype(float)
test = ptf[["positionWeight", "instIssuerCountry"]]
test.groupby(by="instIssuerCountry").sum().sort_values(
    by="positionWeight", ascending=False
).round(4)

                   positionWeight
instIssuerCountry
GBR                        0.2344
FRA                        0.2088
DEU                        0.1876
CHE                        0.0931
ESP                        0.0670
SWE                        0.0486
ITA                        0.0479
NLD                        0.0445
NOR                        0.0239
FIN                        0.0234
0                          0.0176
AUT                        0.0033

In [5]:
ptf["positionWeight"] = ptf["positionWeight"].astype(float)
test = ptf[["positionWeight", "instSectorBicsName1"]]
test.groupby(by="instSectorBicsName1").sum().sort_values(
    by="positionWeight", ascending=False
).round(4)

                        positionWeight
instSectorBicsName1
Financials                      0.2447
Consumer Discretionary          0.1548
Industrials                     0.1196
Health Care                     0.1186
Communications                  0.0925
Energy                          0.0924
Consumer Staples                0.0472
Technology                      0.0458
Materials                       0.0429
Utilities                       0.0240
0                               0.0176

In [6]:
bins = [
    0,
    2000000000,
    10000000000,
    200000000000,
    float("inf"),
]  # Added float('inf') for Mega Cap
labels = [
    "Small Cap (200m - 2b)",
    "Mid Cap (2b - 10b)",
    "Large Cap (10b - 200b)",
    "Mega Cap (> $ 200b)",
]

# Create a copy of the relevant columns
test = ptf[["positionWeight", "instMktCap"]].copy()
test["instMktCap"] = test["instMktCap"].astype(float)

# Map the instMktCap to the defined labels
test["Style"] = pd.cut(test["instMktCap"], bins=bins, labels=labels, right=False)
test[["positionWeight", "Style"]].groupby(by="Style").sum().round(4)

/tmp/ipykernel_2415/2509053802.py:21: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  test[["positionWeight", "Style"]].groupby(by="Style").sum().round(4)

                        positionWeight
Style
Small Cap (200m - 2b)           0.0210
Mid Cap (2b - 10b)              0.1118
Large Cap (10b - 200b)          0.7707
Mega Cap (> $ 200b)             0.0965